### PR TITLE
[lit-next] Improve the ESLint and Prettier setup

### PR DESCRIPTION
**Pull request by abdonrd**
In this PR I address a few related things:

---

- Move the `lint` command to the root.
  - Now there is one entry point to lint all the project.
  - Having lerna in between, made us lose the colors and links in the terminal that ESLint provides. Now we have them again; a nice improvement to the development experience!

---

- Move the `format` command to the root.
  - Now there is one entry point to lint all the project.
  - In addition to Prettier, now we also auto-format with the ESLint `--fix` option.

---

- Now we also use the `.gitignore` file in ESLint and Prettier.

---

- Now we have the `.gitignore` files unified.

---

- ~~Now use Prettier plugin ([`prettier-plugin-package`](https://github.com/shellscape/prettier-plugin-package)) to auto-format the `package.json` files.~~
  - Temporally removed because it also sorts the `files` field: [prettier-plugin-package #12](https://github.com/shellscape/prettier-plugin-package/issues/12).
With my proposal PR: [prettier-plugin-package #17](https://github.com/shellscape/prettier-plugin-package/pull/17)
PR merged! Waiting the next release...

---

- Now we also lint and format the root files (like the `rollup-common.js`, etc).

---

- Now all the project is linted and formatted.
  - In new PRs we can try to remove temporally ignored rules, inlined ignored comments, etc.

---

- Now we have `husky` (as pre-commit hook) & `lint-staged` (to run linter & formatter only on the staged files).
This will avoid commits that don't comply the rules of the linter and the formatter. 🎉🎉

---

### CODE REVIEW

**Comment by abdonrd** [comment]
Friendly ping to @aomarks!

**Review by aomarks — APPROVED** [review]
Wow, great work!

I like the idea of trying out husky and lint-staged. It looks like it's going to automatically format before commit? Will that just happen silently, or does it fail the commit command and just stage the fixed changes?

I'm going to hold off on merging so that @justinfagnani can review, since there are a lot of changes here.

**Comment by abdonrd** [comment]
Thanks Alexander!

Yes, it makes changes automatically and silently.
But if the linter of formatter fails, it doesn't allow to commit. For example, if an ESLint rule is not met that cannot be automatically with the `--fix` flag.

**Comment by abdonrd** [comment]
Updated now with the latest changes from `lit-next` branch!

**Comment by abdonrd** [comment]
Updated now with the latest changes from `lit-next` branch!

**Comment by aomarks** [comment]
@abdonrd thanks for merging again, I think there's just a conflict with the package-lock being out of sync, just need to delete it and re-install I think.

**Comment by abdonrd** [comment]
Yay, thanks @aomarks! 🎉

Remember to update the dependencies locally so that everything works correctly!

**Pull request merged**
