### PR TITLE
Fix support of try/catch block in Edge

### PR DESCRIPTION
**Pull request by astrinxit66**
As discussed in #912, this is necessary for lit-html to run in Edge <= v41.

Fixes https://github.com/Polymer/lit-html/issues/912.

### CODE REVIEW

**Comment by justinfagnani** [comment]
It'd be really great to have failing tests so we don't hit this again. We test [Edge 15 and 17 on Sauce](https://github.com/Polymer/lit-html/blob/master/.travis.yml#L18), which I guess are the EdgeHTML versions and possibly correspond to Edge 40.15063 and 42.17134?

If we could get a Sauce version string that fails before the PR I'll add it.

**Comment by astrinxit66** [comment]
I agree for having a test but to me this is far behind my skills unfortunately, I can't find solutions for those questions: 
- how to target a failure for a specific browser?
- how to catch the failure case as when it fails in Edge it just stuck there? 
- if we assume that Edge can reach the assertion point of our failure test case what should we assert because Edge does not produce any error of any kind (no exception, nothing) for this bug?

I would be very interested to see what we can do!

**Comment by justinfagnani** [comment]
@astrinxit66 I think the only thing we really need is to know a real version of Edge that this fails on. The Sauce Labs `microsoftedge@15` and `microsoftedge@17` browser tags do not hit this error, even though it seems like `microsoftedge@15` _should_ be Edge <= 41 for the consumer version.

**Comment by astrinxit66** [comment]
Ok, I have the bug on `Edge 41.16299.1004.0` with `EdgeHTML 16.16299`.

**Comment by astrinxit66** [comment]
Ok, I have the bug on `Edge 41.16299.1004.0` with `EdgeHTML 16.16299`.

**Comment by jridgewell** [comment]
Ping @justinfagnani

**Pull request merged**
