### PR TITLE
Reimplement directives

### PR DESCRIPTION
**Pull request by mariusGundersen**
This is a reimplementation of how directives work with the goal of being able to track when a directive is detached in a future pull-request, as described in #527.

The core of this pull-request is the change of the `while(isDirective(value)){}` loop into a recursive call (possible since tail recursion is equivalent to iteration). That is, instead of storing only the final value in the part a stack of parts is created with the value stored in the topmost part on the stack. This results in the directive function being called with a new fresh Part and the directive is free to manipulate it however it likes. This means that the `setValue()` and `commit()` methods of Part of a Template can only be called by the Template (in the `update()` method), directives are given their own Parts to work with.

To make this possible the `directive()` function is replaced with a `createDirective` function. This function returns a `DirectiveResult` which the Part converts to a `DirectiveInstance` similar to how the ``html`...``` method returns a `TemplateResult` that is converted into a `DirectiveInstance`. The `createDirective` function makes it possible to keep state per Part using closures instead of WeakMaps and makes it simple to differentiate when a directive is created and when it is merely updated:

```js
// Just a dummy directive example
const myDirective = createDirective(part => {
  // This is where to store state for this directive
  // because this closure is reused for the part
  // every render
  let previousValue, previousMapper;
  return (value, expensiveMapper) => {
    // This is called every time the part is rendered,
    // potentially with a new value
    if(value !== previousValue || expensiveMapper !== previousMapper){
      // Almost everything calls commit right after setValue, so the commitValue method
      // has been introduced to make it simpler
      part.commitValue(expensiveMapper(value));
      previousValue = value;
      previousMapper = expensiveMapper;
    }
  }
});
``` 

There is also a way for a directive to be notified of when it is detached from the DOM, so it is easier to work with directives that asynchronously modifies a part:

```js
const tick = createDirective(part => {
  let i = 0;
  const intval = setInterval(() => part.commitValue(i++ % 2 ? 'tick' : 'tock'), 1000);

  // The lambda is called when the part is detached, clearing the interval
  part.onDetach(() => clearInterval(intval));

  // This directive doesn't take a value, so return an empty function.
  return () => {};
});
```

In this pull-request the onDetach event is quite limited and only called when the Part is directly removed, but it should be fairly easy to expand this to handle any Part being removed in the tree structure of Parts, TemplateInstances and DirectiveInstances.

### CODE REVIEW

**Comment by mariusGundersen** [comment]
I've changed the api slightly by removing the `onDetach()` method from the Part and moving the handling of detachment to the `DirectiveInstance` instead. The new api allows an object with two methods, `update` and `detach`, to be returned when the directive instance is created:

```js
const myDirective = createDirective(part => {
  // return an object with both an update and detach callback
  return {
    update(value) {
      // this is called every time the template is rendered
    },
    detach() {
      // this is called when the directive is detached from the part
    }
  };
});
```

**Comment by mariusGundersen** [comment]
I am unfortunately unable to run `npm format` beceause it assumes a unix machine and doesn't work on a Windows machine. Running tests is also difficult because they requrie Java. This is an unfortunate obstacle to contributing this project.

**Comment by justinfagnani** [comment]
@mariusGundersen from a glance this PR seems like it aligns with some ideas we've had for a directive redesign, but honestly it's quite a large change to review without previous agreement on the design. A code review isn't the best place to review design. I'd rather discuss the shape of the solution before a lot of code is written.

We've been considering aligning directives to templates a little more, including introducing DirectiveResult, and various ways of abstracting state for directives. We need to resolve this before settling on an option.

**Comment by mariusGundersen** [comment]
Sure, no problem, I didn't make this pull request expecting it to be merged directly, but more as a proposal and a basis for discussion. I have made it so as to keep the current api as stable as possible, but if that's not a requirement then there are potential for bigger changes.

What's your preferred way to discuss the design? Is there an open issue I can have a read through?

**Comment by justinfagnani** [comment]
@mariusGundersen thanks for understanding. We have a few related issues open, but nothing comprehensive that touches on the three big areas I see right now: state management, and composition and the disconnect feature. Most of the team discussions have been in person, and not fully captured to issues, so I apologize for that.

Let me open an issue tonight with a summary of things.

**Comment by justinfagnani** [comment]
Closing as out of date and superseded by 2.0

**Pull request closed without merging**
