### PR TITLE
fixes invalidCharacter error in Edge

### PR DESCRIPTION
**Pull request by filaraujo**
Background: 

attributes created with special attribute character will not be processed in Edge. This commit will allow attempt to `attributes.getNamedItem` and if that fails fall back to `node.getAttribute` instead.

fixes issue #295

### CODE REVIEW

**Comment by justinfagnani** [comment]
@filaraujo our Edge tests are passing. Do you have an example that is failing for you?

**Comment by filaraujo** [comment]
ill have to reproduce this again - it was happening locally on a project. I'll update the pr with tests if i can reproduce it again

**Comment by justinfagnani** [comment]
@filaraujo @MartinsThiago any reproduction would be great. Like I said, we have tests that use the `?` suffix and they are passing on Edge. Before merging this change I'd want to see a failing test that passes with the change.

**Comment by justinfagnani** [comment]
As part of another PR, I have a change that should fix by building up a map of bound attributes: https://github.com/Polymer/lit-html/pull/344/files#diff-7548be97e171131880082c935a962f68R326

I like this a little better than causing exceptions, so I'm going to close this PR and we can extract that fix from the other. We still need a failing test though.

**Pull request closed without merging**
