### PR TITLE
Apply theme to API docs

### PR DESCRIPTION
**Pull request by katejeffreys**
https://20181221t150723-dot-polymer-lit-html.appspot.com/api/index.html

### CODE REVIEW

**Comment by arthurevans** [comment]
Thanks! I notice you went back to the default theme, with the nav on the right side. Was that just easier to extend, or were there other things you wanted from the default theme?

**Comment by katejeffreys** [comment]
Er, I didn't notice I'd done it, sorry! I must have extended the wrong
typedoc theme. Will do another PR with minimal theme.

**Comment by justinfagnani** [comment]
@katejeffreys did you mean to close this PR, or are you going to update it?

**Comment by katejeffreys** [comment]
I did mean to update it. I spent some more time on it this morning but couldn't get the minimal theme to build with the main docs theme. 

@arthurevans Sorry I couldn't get this working.

**Comment by arthurevans** [comment]
Going to merge this as-is and iterate. Thanks @katejeffreys!

**Pull request merged**
