### PR TITLE
[lit-next] Use glob braces in package.json files

### PR DESCRIPTION
**Pull request by abdonrd**
Use glob braces in `package.json` `files`.

### CODE REVIEW

**Comment by kevinpschaaf** [comment]
Incorporated this approach with some other cleanup in https://github.com/Polymer/lit-html/pull/1590. Thanks!

**Comment by abdonrd** [comment]
Nice, thanks @kevinpschaaf! 👏🏻 

But why didn't you merge this PR already created?

**Comment by kevinpschaaf** [comment]
Sorry, by the time we looked at it it had merge conflicts and some of it had already been done on other PR's; I was cleaning up the clean scripts and fixing a few missing things and just did the rest of it.

**Comment by abdonrd** [comment]
Ok, thanks Kevin!

**Pull request closed without merging**
