### PR TITLE
Template data type

### PR DESCRIPTION
**Pull request by paulvarache**
Related to #582 
 - Add HTMLTemplateElement as data type
 - Add test
 - Update documentation

### CODE REVIEW

**Comment by paulvarache** [comment]
I signed it!

**Comment by ruphin** [comment]
This adds an additional `instanceof` check to every Part commit. Is there a reason why this feature can't be implemented with a directive? I thought we wanted to keep the core as lightweight as possible, and this adds no additional functionality.

**Comment by ruphin** [comment]
This for example:

```js
const templateMap = new WeakMap();

const fromTemplate = directive(template => part => {
  if (templateMap.get(part) === template) {
    return;
  }
  templateMap.set(part, template)
  const content = template.cloneNode(true).content;
  part.setValue(content);
  part.commit();
}

// Usage:
const myTemplate = document.createElement('template');
myTemplate.innerHTML = '<p></p>'

html`<div>${ fromTemplate(myTemplate) }</div>`;
```

**Comment by justinfagnani** [comment]
Thanks for the PR, but we did decide to not handle `<template>` specially. We can handle templates in directives.

**Pull request closed without merging**
