### PR TITLE
Fixes #630

### LINKED ISSUE #630: Self closing tags
As far as i can see we can't use self closing tags (<custom-element />) in HTML5. I tried using XHTML instead but that have problems with <script type="module"> so i was wondering is there any way we can do this while processing template inside html template literal ? I heard hyperHTML already doing this as you can see at [hyperHTML referance](https://github.com/WebReflection/hyperHTML/blob/7509fcac074217fbc1bcd01d72b0cbd2a122d7fe/cjs/hyper/render.js#L65) .

### PR DESCRIPTION
**Pull request by kaaninel**
Inside getHTML function we replace <tag /> to <tag></tag>

### CODE REVIEW

**Comment by kaaninel** [comment]
But that's not developer friendly and a real bummer for using html without a pre-processor. This pull-request aims to get rid of this need so we can use lit only.

**Comment by web-padawan** [comment]
By supporting self-closing syntax for custom elrments, we could confuse users trying to use them also outside of `lit-html`.

**Comment by ruphin** [comment]
Discussion regarding the desirability of a PR should take place in the relevant issue (#630), and not the PR. This space is reserved for feedback on implementation details.

**Comment by justinfagnani** [comment]
I believe there's a much simpler way of doing this with `String.replace`[1]. Even so, as discussed in #630 I'd rather leave this up to third-party extensions, which can define a new `html` tag with a simple subclass of `TemplateResult`.

[1]: See an example here: https://github.com/developit/htm/blob/c3182e44049301d7a9cc178576c3a2d281ecef3c/src/index.mjs#L38

**Pull request closed without merging**
