### PR TITLE
Use ES2015 `String#endsWith` instead of a local implementation.

### PR DESCRIPTION
**Pull request by bicknellr**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

### CODE REVIEW

**Comment by jridgewell** [comment]
Note, this implementation came from profiling: https://jsbench.github.io/#2845ec98f02d336a31ae52139dfd8056. I'm fine with whichever.

**Comment by bicknellr** [comment]
Huh, that's pretty surprising that native `endsWith` loses to slice. Maybe I should just add a comment about this instead?

**Comment by jridgewell** [comment]
I think it's worth having @justinfagnani decide. There's definitely a speed vs file-size trade off.

**Comment by bicknellr** [comment]
Also, it looks like whatever compiler we're using doesn't insert `endsWith`.

**Comment by justinfagnani** [comment]
`endsWith` isn't supported by IE11: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#Browser_compatibility

And we're not using a compiler that injects polyfills. We use TypeScript, but only to compile out types.

**Pull request closed without merging**
