### PR TITLE
Add section indicator in top nav

### LINKED ISSUE #723: Add current section indicator to docs
"Guide" or "API" could use a highlight, underline or something.

cc @yuinchien for guidance

### PR DESCRIPTION
**Pull request by keanulee**
Staged at https://20190226t111129-dot-polymer-lit-html.appspot.com/guide/getting-started

Fixes #723

### CODE REVIEW

**Comment by justinfagnani** [comment]
On the API page the header links still have hover-over underlines:

screen shot 2019-02-26 at 11 43 31 am

**Comment by keanulee** [comment]
Fixed (underline on hover was coming from the TypeDoc stylesheet).

**Comment by justinfagnani** [comment]
Awesome. LGTM

**Comment by keanulee** [comment]
Promoted staging version.

**Pull request merged**
