### PR TITLE
Prepare 1.1.2 release

### PR DESCRIPTION
**Pull request by straversi**

### CODE REVIEW

**Comment by jridgewell** [comment]
Can we land https://github.com/Polymer/lit-html/pull/966?

**Comment by straversi** [comment]
@jridgewell I don't think I have the authority, and Justin is out this week. Next week?

**Comment by justinfagnani** [comment]
@jridgewell I'll review #966 today. We can get another release out right away too.

**Comment by aomarks** [comment]
Just need to update the changelog date

**Pull request merged**
