### PR TITLE
Test that comments aren't inserted into textContent

### PR DESCRIPTION
**Pull request by jridgewell**
Reopens #214.
Re: https://github.com/Polymer/lit-html/pull/267#issuecomment-386487510

### CODE REVIEW

**Comment by justinfagnani** [comment]
@jridgewell I'm adding in this test, but checking `.textContent` instead of `.innerHTML`, and it passes. CSS engines depend on the `.textContent` of `<style>`, so the presence of comment nodes is fine.

Granted, other tools or libraries which check innerHTML on styles may hit problems, but they should be looking at textContent.

**Comment by jridgewell** [comment]
👍

**Comment by jridgewell** [comment]
Updated the test.

**Comment by justinfagnani** [comment]
@jridgewell I submitted already in #314, thanks!

**Pull request closed without merging**
